### ISSUE TITLE
BUG: Leaf drops

### ISSUE THREAD

**Issue by skyjay1** [lilrichy/RegrowableLeaves#3]
Leaves do not drop anything, even when shears are used. 
Possible solution:  remove lines 23 and 28 of EventHandler.java "e.setCanceled(true);"

**Comment by lilrichy** [comment]
I can not remove lines 23 and 28 because the air blocks do not get placed.

I think I will add a check to see if shears are used then just drop the block, basically mimicking what shears would normally do.

**Comment by lilrichy** [comment]
I pushed a new version to github: https://github.com/lilrichy/RegrowableLeaves/blob/master/src/main/java/com/blogspot/richardreigens/regrowableleaves/EventHandler.java 
I'll prolly upload this to curse and see if that will fix this problem or not I was just trying out a few things before I upload it, let me know if you think this will work or not.

**Comment by lilrichy** [comment]
I also figured out how to get it to drop the normal items when breaking leaves. 

So now it will drop saplings and apples like normal when broken and the leaf block when broken with shears.

I am thinking I should add a config option for the item drops though. 

https://github.com/lilrichy/RegrowableLeaves/commit/328b7556f537ef7c7f3a6b3a233c708a632ee9a5

Uploaded the new version to curse.

**Comment by lilrichy** [comment]
Closing this since I believe the issue was fixed in version 1.4
